//Create a user
POST https://icecreamapp-database.herokuapp.com/users
Content-Type: application/json

{
    "name": "User",
    "email": "admin@admin.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "user"
}

###
//Get All users
GET https://icecreamapp-database.herokuapp.com/users

###
//GET SINGLE USER

GET https://icecreamapp-database.herokuapp.com/users/d32db6ac-8bf1-4ece-8a90-9e4b676a4725
###
//update user
PATCH https://icecreamapp-database.herokuapp.com/users/d32db6ac-8bf1-4ece-8a90-9e4b676a4725
Content-Type: application/json

{
    "today": "0"
}

###
//DELETE USER

DELETE https://icecreamapp-database.herokuapp.com/users/3da0f8a1-a284-4074-bcda-d9122a950f3e

###
//Login User

POST https://icecreamapp-database.herokuapp.com/login
Content-Type: application/json

{
    "email": "user@user.com",
    "password": "123456"
}

###
//Login Admin
POST https://icecreamapp-database.herokuapp.com/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "icecream123456"
}

###
//get user
GET https://icecreamapp-database.herokuapp.com/me

###
//logout user
DELETE https://icecreamapp-database.herokuapp.com/logout

###
//get all products
GET https://icecreamapp-database.herokuapp.com/products

###
//get ONE product
GET https://icecreamapp-database.herokuapp.com/products/059d97f7-a54d-4995-8304-25913407b6a3


###
//create product
POST https://icecreamapp-database.herokuapp.com/products
Content-Type: application/json

{
    "name": "cacca",
    "price": 3,
    "quantity": 50
}

###
//update product
PATCH https://icecreamapp-database.herokuapp.com/products/9938a883-0005-426b-b6dc-749c4dd8f04c
Content-Type: application/json

{
    "imgLink": "https://source.unsplash.com/Wq0tcKzIa0M"
}

###
//delete product
DELETE https://icecreamapp-database.herokuapp.com/products/06aae1c6-8d39-427d-b244-5e3fce7d9792